Create Manage Tags Page
community-boating/cbidb-staff-web pull request #2
Opened 2021-09-17 20:57 UTC by yoshirahh

### Description
Added the "Manage Tags" page to the Admin section, utilizing the REST endpoint at `/api/rest/tags`. This page allows for simple creation, reading, and updating of tags.

**JIRA Tracker:**  [STAFF-12](https://community-boating.atlassian.net/browse/STAFFWEB-12?atlOrigin=eyJpIjoiNTA3NmVjODI0NGYwNDFmODk5YWNiM2E0OTFjZDQ4NDgiLCJwIjoiaiJ9)

### Type of Request
- [x] New feature
- [ ] Bug fix
- [ ] Other: 

### New Features
* Adds new page: Manage Tags at `/admin/tags`

### Other Changes
* Added `cardTitle` prop to the `ReportWithModalForm` component, configuring the title on the form table's parent card
* Configured `postcss:^8.3.6` as a dev dependency: this is required to run the dev environment

2021-09-18 14:04 UTC, coleji requested changes
A couple minor things, mostly let's see if we can get EditorConfig working to handle whitespace in new files in advance of setting up an auto formatter.  Looks great!

2021-09-18 14:04 UTC, coleji commented on src/app/SidebarCategories.ts
> +		manageTagsPageRoute,
Move this to rendered children so the page will appear in the sidebar

2021-09-18 14:04 UTC, coleji commented on src/app/routes/admin/tags.tsx
> +    {
Change these new files indented with 4 spaces to indented with tab characters for consistency.  I added a .editorconfig file to the master branch which should hopefully make it so you dont need to change your editor global config, should be able to apply this config on a per-project basis (so it will work without an auto beautifier).  If you use VSCode, might need the editorconfig plugin (https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig).  If you use a different editor, I think this format is pretty standard

2021-09-18 14:04 UTC, coleji commented on src/components/ReportWithModalForm.tsx
> +}
Its a minor thing but leave the trailing newline chars at the end of each file.  Editorconfig should handle that if you can get it working

2021-09-18 14:04 UTC, coleji commented on src/pages/admin/ManageTagsPage.tsx
> +    function blockDefaultEnter(e: React.KeyboardEvent) {
I was baffled at first as to why this is necessary; I can see that it is, but I wasn't clear why the manage instructors page does not need it.  I learned there is a feature that seems to be standard in all browsers, where if a form has a single input field, then hitting enter will trigger an "implicit submit".  Rather than have to block enter on each form separately, I refactored the component to supply the form element (and even slot in the modal's actual submit function into the form submit) and updated manage-instructors on release/next.  Can you merge release/next in and do the same refactor here?  Just replace the ` <Form>` tag with a `<React.Fragment>` (and rename the prop)

2021-09-18 14:04 UTC, coleji commented on package.json
> +    "postcss": "^8.3.6",
Did you get an error from not having this?  I've never had an issue without it, but I've only ever attempted to build in linux.  Just curious

2021-09-18 14:09 UTC, coleji commented
@yoshirahh oh and btw if you didn't already stumble on this, if you add `instantSudo=true` to the bottom of your config.ini file, it will start off with sudo on, so you don't have to re-elevate every time you refresh the page.  Super handy for developing admin pages

2021-10-03 21:21 UTC, yoshirahh commented on src/app/SidebarCategories.ts
> +		manageTagsPageRoute,
Resolved in ce57cc51ed1e0b82d3cf647990308cb0afbd8e98

2021-10-03 21:21 UTC, yoshirahh commented on src/app/routes/admin/tags.tsx
> +    {
Resolved in 8203bf51bef2b7150ad4613fc417dafe9e8243b3

2021-10-03 21:22 UTC, yoshirahh commented on src/components/ReportWithModalForm.tsx
> +}
Resolved in e2b2e81f77fedc7dd4137bd455cc14304960677e

2021-10-03 21:22 UTC, yoshirahh commented on src/pages/admin/ManageTagsPage.tsx
> +    function blockDefaultEnter(e: React.KeyboardEvent) {
Resolved in 6246f9efdd13f8431cbb5252e8b259685a5342e2

2021-10-03 21:23 UTC, yoshirahh commented on package.json
> +    "postcss": "^8.3.6",
Yeah, it was kinda weird. I couldn't run any of the NPM scripts until I had postcss installed somewhere on the machine. I'm using WSL, so it's kinda linux, but my best guess is that it's just not installed globally in there where it is in most other cases.

2021-10-05 19:23 UTC, merged